/*DROP TABLE IF EXISTS tablefour;
CREATE TABLE tablefour(Nombre_del_municipio STRING, Poblacion_total INT, Porcentaje_de_poblacion_analfabeta_de_15_anos_o_mas INT, Porcentaje_de_poblacion_de_15_anos_o_mas_sin_educacion_basica INT, Porcentaje_de_ocupantes_en_viviendas_sin_drenaje_ni_excusado INT, Porcentaje_de_ocupantes_en_viviendas_sin_energia_electrica INT, Porcentaje_de_ocupantes_en_viviendas_sin_agua_entubada_en_el_ambito_de_la_vivienda INT, Porcentaje_de_viviendas_con_hacinamiento INT, Porcentaje_de_ocupantes_en_viviendas_con_piso_de_tierra INT, Porcentaje_de_poblacion_que_vive_en_localidades_menores_a_5000_habitantes INT, Porcentaje_de_poblacion_ocupada_con_ingresos_de_hasta_2_salarios_minimos INT, Indice_de_marginacion_2020 INT, Grado_de_marginacion_2020 STRING                                        
) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
ALTER TABLE tablefour SET TBLPROPERTIES("skip.header.line.count"="1");                                     
LOAD DATA INPATH '/user/maria_dev/fuentes_de_informacion/4/4_in/IIEGMargIndicadores2020NotUTF8.csv' OVERWRITE INTO TABLE tablefour;
select * from tablefour limit 10;
DROP TABLE IF EXISTS tablefourgroupedby;
CREATE TABLE tablefourgroupedby(Grado_de_marginacion_2020 STRING, Poblacion_total INT, Porcentaje_de_poblacion_analfabeta_de_15_anos_o_mas INT, Porcentaje_de_poblacion_de_15_anos_o_mas_sin_educacion_basica INT, Porcentaje_de_ocupantes_en_viviendas_sin_drenaje_ni_excusado INT, Porcentaje_de_ocupantes_en_viviendas_sin_energia_electrica INT, Porcentaje_de_ocupantes_en_viviendas_sin_agua_entubada_en_el_ambito_de_la_vivienda INT, Porcentaje_de_viviendas_con_hacinamiento INT, Porcentaje_de_ocupantes_en_viviendas_con_piso_de_tierra INT, Porcentaje_de_poblacion_que_vive_en_localidades_menores_a_5000_habitantes INT, Porcentaje_de_poblacion_ocupada_con_ingresos_de_hasta_2_salarios_minimos INT, Indice_de_marginacion_2020 INT
) STORED AS TEXTFILE;
ALTER TABLE tablefourgroupedby SET TBLPROPERTIES("skip.header.line.count"="1");
INSERT OVERWRITE TABLE tablefourgroupedby SELECT a.grado_de_marginacion_2020, SUM(a.poblacion_total) as poblacion_total, SUM(a.porcentaje_de_poblacion_analfabeta_de_15_anos_o_mas) as porcentaje_de_poblacion_analfabeta_de_15_anos_o_mas, SUM(a.porcentaje_de_poblacion_de_15_anos_o_mas_sin_educacion_basica) as porcentaje_de_poblacion_de_15_anos_o_mas_sin_educacion_basica, SUM(a.porcentaje_de_ocupantes_en_viviendas_sin_drenaje_ni_excusado) as porcentaje_de_ocupantes_en_viviendas_sin_drenaje_ni_excusado, SUM(a.porcentaje_de_ocupantes_en_viviendas_sin_energia_electrica) as porcentaje_de_ocupantes_en_viviendas_sin_energia_electrica, SUM(a.porcentaje_de_ocupantes_en_viviendas_sin_agua_entubada_en_el_ambito_de_la_vivienda) as porcentaje_de_ocupantes_en_viviendas_sin_agua_entubada_en_el_ambito_de_la_vivienda, SUM(a.porcentaje_de_viviendas_con_hacinamiento) as porcentaje_de_viviendas_con_hacinamiento, SUM(a.porcentaje_de_ocupantes_en_viviendas_con_piso_de_tierra) as porcentaje_de_ocupantes_en_viviendas_con_piso_de_tierra, SUM(a.porcentaje_de_poblacion_que_vive_en_localidades_menores_a_5000_habitantes) as porcentaje_de_poblacion_que_vive_en_localidades_menores_a_5000_habitantes, SUM(a.porcentaje_de_poblacion_ocupada_con_ingresos_de_hasta_2_salarios_minimos) as porcentaje_de_poblacion_ocupada_con_ingresos_de_hasta_2_salarios_minimos, SUM(a.indice_de_marginacion_2020) as indice_de_marginacion_2020 FROM tablefour a GROUP BY a.grado_de_marginacion_2020;
select * from tablefourgroupedby limit 10;*/

USE jalisco;
DROP TABLE IF EXISTS balance_neto;
create table balance_neto(Nation_ID string, Nation string, State_ID int, State string, Municipality_ID int, Municipality int, Exports int, Imports int, Balance int) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
ALTER TABLE balance_neto SET TBLPROPERTIES("skip.header.line.count"="1");
LOAD DATA INPATH '/user/maria_dev/jalisco/balance_neto.csv' OVERWRITE INTO TABLE balance_neto;